dataset_name: "1.0"
batch_size: 64
num_epochs: 200
num_workers: 10
early_stopping_patience: 10
use_metadata: true
backbone: "resnet50" # convnext, vit, efficientnet, resnet50, resnet34
learning_rate: 1e-4
